{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_sec", "time": 0.08534860610961914, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != b'\\x04\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8[162 chars]\\xf9'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastest00/sec-format-jsong-programming-blockchain-demo/test/index_test.py\", line 16, in test_sec\n    self.assertEqual(point.sec(compressed=False), bytes.fromhex(uncompressed))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != b'\\x04\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8[162 chars]\\xf9'\n"}]}